# --- PulseMesh Intelligence Sources Configuration ---

SOURCE_MAP = {
    "nytimes.com": "NYT",
    "bbc.co": "BBC",
    "techcrunch.com": "TechCrunch",
    "thehill.com": "The Hill",
    "wired.com": "Wired",
    "theverge.com": "Verge",
    "venturebeat.com": "VentureBeat",
    "theguardian.com": "Guardian",
    "npr.org": "NPR",
    "pbs.org": "PBS",
    "arstechnica.com": "Ars",
    "technologyreview.com": "MIT Tech",
    "cnbc.com": "CNBC",
    "marketwatch.com": "MarketWatch",
    "reuters.com": "Reuters",
    "apnews.com": "AP",
    "dw.com": "DW",
    "espn.com": "ESPN",
    "skysports.com": "Sky Sports",
    "hollywoodreporter.com": "THR",
    "variety.com": "Variety",
    "rollingstone.com": "Rolling Stone",
    "deadline.com": "Deadline",
    "phys.org": "Phys.org",
    "sciencedaily.com": "SciDaily",
    "vogue.com": "Vogue",
    "gq.com": "GQ",
    "yahoo.com": "Yahoo",
    "nature.com": "Nature",
    "eonline.com": "E! News",
    "google.com": "Google News",
    "nypost.com": "NY Post",
    "gdacs.org": "GDACS",
    "usgs.gov": "USGS",
    "reliefweb.int": "ReliefWeb",
    "un.org": "UN News",
    "crisisgroup.org": "Crisis Group",
    "who.int": "WHO",
    "tsunami.gov": "NOAA",
    "nhc.noaa.gov": "NHC",
    "cdc.gov": "CDC",
    "thehindu.com": "The Hindu",
    "economictimes.indiatimes.com": "Economic Times",
    "gadgets360.com": "Gadgets 360",
    "espncricinfo.com": "Cricinfo",
    "hindustantimes.com": "HT",
    "livemint.com": "Livemint",
    "prasarbharati.gov.in": "PB News",
}

FEEDS = {
    "Politics": [
        "https://news.google.com/rss/topics/CAAqIQgKIhtDQkFTRGdvSUwyMHZNRFZ4ZERBU0FtVnVLQUFQAQ?hl=en-US&gl=US&ceid=US:en",
        "https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml",
        "https://feeds.bbci.co.uk/news/politics/rss.xml",
        "https://feeds.npr.org/1014/rss.xml",
        "https://www.pbs.org/newshour/feeds/rss/headlines",
        "https://thehill.com/feed/",
        "https://www.theguardian.com/politics/rss",
        "https://www.thehindu.com/news/national/feeder/default.rss",
        "https://www.livemint.com/rss/politics",
    ],
    "Tech": [
        "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGRqTVhZU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en",
        "https://techcrunch.com/feed/",
        "https://feeds.arstechnica.com/arstechnica/index",
        "https://www.wired.com/feed/rss",
        "https://www.technologyreview.com/feed/",
        "https://www.theverge.com/rss/index.xml",
        "https://feeds.feedburner.com/venturebeat/SZYF",
        "https://feeds.feedburner.com/gadgets360-latest",
    ],
    "World": [
        "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx1YlY4U0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en",
        "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
        "https://feeds.bbci.co.uk/news/world/rss.xml",
        "https://feeds.npr.org/1004/rss.xml",
        "https://www.pbs.org/newshour/feeds/rss/world",
        "https://www.theguardian.com/world/rss",
        "https://www.dw.com/rss/rss.xml",
        "https://www.thehindu.com/news/international/feeder/default.rss",
    ],
    "Business": [
        "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx6TVdZU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en",
        "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
        "https://feeds.bbci.co.uk/news/business/rss.xml",
        "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114",
        "https://feeds.marketwatch.com/marketwatch/topstories/",
        "https://economictimes.indiatimes.com/markets/rssfeeds/19770215.cms",
        "https://www.livemint.com/rss/markets",
    ],
    "Science": [
        "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx6TVdZU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en",
        "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
        "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
        "https://phys.org/rss-feed/",
        "https://www.sciencedaily.com/rss/top/science.xml",
        "https://www.nature.com/nature.rss",
        "https://www.thehindu.com/sci-tech/science/feeder/default.rss",
    ],
    "Sports": [
        "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRFp1ZEdvU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en",
        "https://www.espn.com/espn/rss/news",
        "https://www.skysports.com/rss/12040",
        "https://rss.nytimes.com/services/xml/rss/nyt/Sports.xml",
        "https://feeds.bbci.co.uk/news/sport/rss.xml",
        "https://www.espncricinfo.com/rss/content/story/feeds/6.xml",
    ],
    "Entertainment": [
        "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNREp6TVdZU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en",
        "https://www.hollywoodreporter.com/feed/",
        "https://www.eonline.com/syndication/feeds/rssfeeds/topstories.xml",
        "https://variety.com/feed/",
        "https://rss.nytimes.com/services/xml/rss/nyt/Arts.xml",
        "https://deadline.com/feed/",
        "https://www.rollingstone.com/music/music-news/feed/",
        "https://www.hindustantimes.com/rss/entertainment/rssfeed.xml",
    ],
    "Lifestyle": [
        "https://rss.nytimes.com/services/xml/rss/nyt/Lifestyle.xml",
        "https://www.vogue.com/feed/rss",
        "https://www.gq.com/feed/rss",
        "https://nypost.com/living/feed/",
        "https://feeds.npr.org/1138/rss.xml",
        "https://www.theguardian.com/lifeandstyle/rss",
        "https://www.thehindu.com/life-and-style/feeder/default.rss",
    ],
    "CrisisWatch": [
        "https://www.gdacs.org/xml/rss.xml",
        "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.atom",
        "https://reliefweb.int/updates/rss.xml",
        "https://news.un.org/feed/subscribe/en/news/topic/peace-and-security/feed/rss.xml",
        "https://www.crisisgroup.org/rss",
        "https://www.who.int/feeds/entity/csr/don/en/rss.xml",
        "https://www.tsunami.gov/rss/",
        "https://www.nhc.noaa.gov/index-at.xml",
        "https://tools.cdc.gov/api/v2/resources/media/132608.rss",
        "https://news.google.com/rss/search?q=site:imd.gov.in+OR+site:ndma.gov.in+emergency+OR+disaster&hl=en-IN&gl=IN&ceid=IN:en",
    ],
}
